### ISSUE TITLE
Calculator Training

### ISSUE THREAD

**Issue by Otwald** [rewriteNG/Frontend#2]
Request angefragt von Semih.
Ansprechpartner: Semih oder Usako Heika

Anfrage:
Rechner in NG wo die Traintage eingetragen werden und das Tool die Werte auspuckt. Gerne mit Vor- und Nachteilen kombinierbar

**Comment by Jackylyn1** [comment]
Die Programmierung ist abgeschlossen, ich habe es der Community zum Testen gegeben und schließe es ab, sobald es getestet wurde.
